name: "Validate PR"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: ["main"]

jobs:
  check_commit_messages:
    runs-on: ubuntu-latest
    name: check source-code formatting
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Run Linter
        run: devenv tasks run check:conventional-commit

  check_code_style:
    runs-on: ubuntu-latest
    name: check source-code formatting
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Run Linter
        run: devenv tasks run check:code-lint

  check_python_unittets:
    runs-on: ubuntu-latest
    name: check python unit-tests
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Run Tests
        run: devenv tasks run check:unit-tests
